apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-namespaces
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: managed-namespaces/overlays
    repoURL: 'https://github.dev/aric49/redhat-summit-gitops/'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
